# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Hide
tagline:          'Datenanalyse mit R und Python'
description:      'Spielwiese für Datenanalyse mit R und Python'
url:              
baseurl:          /

author:
  name:           'Hans Novak'
  url:            

paginate:         5

timezone: Europe/Berlin

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/HansNovak/HansNovak.github.io
