# Dependencies
#markdown:         redcarpet
#highlighter:      pygments

# Permalinks
#permalink:        pretty


# Setup
title:            Hide
tagline:          'Datenanalyse mit R und Python'
description:      'Datenanalyse mit R und Python'
url:              
baseurl:          /

author:
  name:           'Hans Novak'
  url:            

paginate:         5

gems: [jekyll-paginate, jekyll-gist]

timezone: Europe/Berlin

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/HansNovak/HansNovak.github.io
