# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Hide
tagline:          'Ein Kritzelbuch'
description:      'Fundstücke aus den Weiten des Internets.'
url:              
baseurl:          /

author:
  name:           'Hans Novak'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
